<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="actions">
    <?php  $_order = $block->getOrder() ?>
    <?php if ($this->helper('Magento\Sales\Helper\Reorder')->canReorder($_order->getEntityId())) : ?>
        <a href="#" data-post='<?php /* @escapeNotVerified */ echo
        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
            ->getPostData($block->getReorderUrl($_order))
        ?>' class="action order">
            <span><?php /* @escapeNotVerified */ echo __('Reorder') ?></span>
        </a>
    <?php endif ?>
    <a class="action print"
       href="<?php /* @escapeNotVerified */ echo $block->getPrintUrl($_order) ?>"
       onclick="this.target='_blank';">
        <span><?php /* @escapeNotVerified */ echo __('Print Order') ?></span>
    </a>
    <?php if ($_order->getStatusLabel()=='Pending') : ?>
        <a class="action cancel"
        href="<?php /* @escapeNotVerified */ echo $block->getCancelUrl($_order) ?>"
        onclick="this.target='_blank';">
            <span><?php /* @escapeNotVerified */ echo __('Cancel Order') ?></span>
        </a>
    <?php endif ?>
    <?php echo $block->getChildHtml(); ?>
</div>

<script type = 'text/javascript'>
    require([
    		'jquery',
    		'Magento_Ui/js/modal/confirm'
    	],
    	function ($, confirmation) {
    	$('.cancel').click(function (event) {
    		event.preventDefault();

            var url = event.currentTarget.href;
    		confirmation({
    			title: 'Cancel order',
    			content: 'Do you wish to cancel this order?',
    			actions: {
    				confirm: function () {
                        window.location.href = url;
    				},
    				cancel: function () {},
    				always: function () {}
    			}
    		});
    		return false;
    	});
    });
</script>